# -- Markup --
# These settings are required for the theme to function.

[goldmark]
  [goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
    autoHeadingID = true # 默认通常是开启的

    [goldmark.parser.attribute]
      block = true

  [goldmark.renderer]
    unsafe = true

  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 1
  endLevel = 4
